services:

    admin.shop.category:
        class: AdminBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Kategorie, group: "Eshop", show_in_dashboard: "true" }
        public: true

    admin.shop.product:
        class: AdminBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Produkty, group: "Eshop", show_in_dashboard: "true" }
        calls:
          - [ setTemplate, [edit, "AdminBundle::ProductAdmin/edit.html.twig"]]
        public: true

    admin.shop.shipping:
        class: AdminBundle\Admin\ShippingAdmin
        arguments: [~, AppBundle\Entity\Shipping, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Dopravy, group: "Eshop", show_in_dashboard: "true" }
        public: true

    admin.shop.payment:
        class: AdminBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Platby, group: "Eshop", show_in_dashboard: "true" }
        public: true

    admin.shop.order:
        class: AdminBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Objednávky, group: "Eshop", show_in_dashboard: "true" }
        public: true

    admin.shop.order_item:
        class: AdminBundle\Admin\OrderItemAdmin
        arguments: [~, AppBundle\Entity\OrderItem, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Objednávky položka, show_in_dashboard: "false" }
        public: true

    extension.listener:
        class: AdminBundle\EventListener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]


#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

