services:

    admin.shop.order:
        class: AdminBundle\Admin\OrderAdmin
        arguments: [~, AppBundle\Entity\Order, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Objednávky, group: "Zákazník", show_in_dashboard: "true" }
        calls:
          - [ setOrderManager, [ "@order.manager" ]]
        public: true

    admin.shop.category:
        class: AdminBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Kategorie, group: "Katalog", show_in_dashboard: "true" }
        public: true

    admin.shop.product:
        class: AdminBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, AdminBundle\Controller\CRUDController]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Produkty, group: "Katalog", show_in_dashboard: "true" }
        calls:
          - [ setTemplate, [edit, "AdminBundle::ProductAdmin/edit.html.twig"]]
        public: true

    admin.shop.event:
            class: AdminBundle\Admin\EventAdmin
            arguments: [~, AppBundle\Entity\Event, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Události, group: "Katalog", show_in_dashboard: "true" }
            public: true

    admin.shop.material:
        class: AdminBundle\Admin\MaterialAdmin
        arguments: [~, AppBundle\Entity\Material, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Materiál, group: "Katalog", show_in_dashboard: "true" }
        public: true


    admin.shop.shipping:
        class: AdminBundle\Admin\ShippingAdmin
        arguments: [~, AppBundle\Entity\Shipping, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Dopravy, group: "Dopravy a platby", show_in_dashboard: "true" }
        public: true

    admin.shop.payment:
        class: AdminBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment, ~ ]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Platby, group: "Dopravy a platby", show_in_dashboard: "true" }
        public: true

    admin.shop.order_status:
        class: AdminBundle\Admin\OrderStatusAdmin
        arguments: [~, AppBundle\Entity\OrderStatus, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Stavy objednávek, group: "Nastavení", show_in_dashboard: "true" }
        public: true

    admin.shop.order_item:
        class: AdminBundle\Admin\OrderItemAdmin
        arguments: [~, AppBundle\Entity\OrderItem, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Objednávky položka, show_in_dashboard: "false" }
        public: true

    admin.shop.order_status_history:
        class: AdminBundle\Admin\OrderStatusHistoryAdmin
        arguments: [~, AppBundle\Entity\OrderStatusHistory, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Historie objednávky, show_in_dashboard: "false" }
        public: true

    admin.shop.attribute:
        class: AdminBundle\Admin\AttributeAdmin
        arguments: [~, AppBundle\Entity\Attribute, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Atribut, show_in_dashboard: "false" }
        public: true

    admin.shop.attribute_option:
        class: AdminBundle\Admin\AttributeOptionAdmin
        arguments: [~, AppBundle\Entity\AttributeOption, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Atribut option, show_in_dashboard: "false" }
        public: true

    extension.listener:
        class: AdminBundle\EventListener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]


#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

