<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function queryFindAll()
    {
        $qb = $this->createQueryBuilder('c');

        return $qb->getQuery();
    }

    public function findAllActive($locale = 'cs')
    {
        return $this->findBy(array('isActive' => true, 'locale' => 'cs'), array('sort' => 'ASC'));
    }

}
