services:
  cart.manager:
    class:    AppBundle\Manager\CartManager
    autowire: true

  order.manager:
    class:    AppBundle\Manager\OrderManager
    autowire: true

  shop.mailer:
    class:    AppBundle\Service\Mailer
    autowire: true

  shop.gopay:
    class:    AppBundle\Service\Gopay
    autowire: true

  shop.zasilkovna:
      class:    AppBundle\Service\Zasilkovna
      autowire: true

  customer_authenticator:
    class:    AppBundle\Security\CustomerAuthenticator
    autowire: true

  unique.email.validator:
    class: AppBundle\Validator\Constraints\CustomerEmailValidator
    autowire: true
    tags:
      - { name: validator.constraint_validator, alias: unqiue.email.validator }

  app.security.login_handler:
    class: AppBundle\Security\LoginHandler
    public: false
    arguments:
        - '@router'
        - '@session'
        - '@cart.manager'
